In [1]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 29.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 55.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 39.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 8.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

**Why have neural networks, even though they were invented early on, only now caught on?**
- too little quantity of data to train ANN's on
- too little computing power
- 

**What is a percepton and a threshold logic unit (TLU)? Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)**
- Perceptron:
  - Is an algorithm that is used to define classify given input datapoints. The classification is being performed with the input value, weights, biases and activation function
- TLU:
  - receives multiple inputs (weights w and bias b) computes a linear funcion (w^t*x+b). And then it applies the step function /activation function and outputs a binary value
- Linear Function with threshold = 0 (step function (If z<=0 --> = else 1)) 
  - *x1*w1+x2*w2-b*
  - w1=2, w2=0,3
  - b=5
    - f(1,3)=-2,1 --> 0
    - f(4,6)=4,8--> 1
    - f(2,2)=-0,4--> 0


**What is a fully connected layer and a output layer? **
- fully connected layer:
 - every TLU is connected to every input
- outpt layer
  - Last layer of the ANN where the TLU's outputs the results

**Why can we easily combine the equations of multiple instances into a fully connected layer?**
- Linear algebra ? 

**What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?**
- Perceptron could not solve simple problems such as XOR classification problems. 
  - However multilayer perceptron solve this issue

**What is a deep neuronal network? What are hidden layers? What means feedforward neural network (FNN).**
 - Hidden layers
  - All layers that are no input nor output layers
- Deep neural network = An NN that contains 100's of hidden layers

**Try to explain how backpropagation works! (In Addition, you can have a look to the following example, which tries manually to compute the backprogation of a simple linear network.** https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ OR you can also read through the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy))
1. Forward pass. In this phase we feed the inputs through the network, make a prediction and measure its error with respect to the true label.
2. Backward pass. We propagate the gradients of the error with respect to each one of the weights backward from the output layer to the input layer.
3. Gradient descent step. We slightly tweak the connection weights in the network by taking a step in the opposite direction of the error gradients

- mini batch = divide training set into randomly selected smaller chunks (because of computational reasons)
- Backpropagation calculates derivates of a ANN, to train a feedforwards neural network we use stochastic gradient descent --> find the lowests point of a function so that the error is minimized
- A loss function (e.g. mean squared error) represents the distance between the prediction and the true labels. Backpropagation let's us calculate the gradient of the loss function with respect to each of the networks weights. With a lot of iterations each weights is updated individually to reduce the loss function
- Chain rule of calculus is used to decrease the costs with respect to the weights of a given instance of a training set (e.g. identifying hand written 2's). The same then is applied to decrease the costs with respect due to the biases



**Why do we need activation functions, wouldn't it be easier just using linear functions?**
 - Linear function can only be applied when the dataset can be distinguished in two classes with a linear function. However most datasets are much more complicated to distinguish two or more classes. Most of the time a linear function is not suitable then. Therefore, we need activation functions (such as ReLU or Sigmoid) which can be tweaked such that a function is not linear 

## Ideas for the learning portfolio: 

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models. 

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?


In [3]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

#hide
from fastai.vision.all import *
from fastbook import *

matplotlib.rc('image', cmap='Greys')

In [4]:
from sklearn.model_selection import train_test_split

#1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.
path = untar_data(URLs.MNIST)
Path.BASE_PATH = path
path.ls()

ones = ((path/'training'/'1').ls() + (path/'testing'/'1').ls()).sorted()
sevens = ((path/'training'/'7').ls() + (path/'testing'/'7').ls()).sorted()

train_ones, test_ones = train_test_split(ones, test_size=0.2, random_state=42)
train_sevens, test_sevens = train_test_split(sevens, test_size=0.2, random_state=42)

#convert images to pytorch tensor (numerical values)
train_ones_tensor = [tensor(Image.open(o)) for o in train_ones]
stacked_train_ones_tensor = torch.stack(train_ones_tensor).float()/255

test_ones_tensor = [tensor(Image.open(o)) for o in test_ones]
stacked_test_ones_tensor = torch.stack(test_ones_tensor).float()/255

train_sevens_tensor = [tensor(Image.open(o)) for o in train_sevens]
stacked_train_sevens_tensor = torch.stack(train_sevens_tensor).float()/255

test_sevens_tensor = [tensor(Image.open(o)) for o in test_sevens]
stacked_test_sevens_tensor = torch.stack(test_sevens_tensor).float()/255

#stacked_test_sevens_tensor.shape

#mean1 = stacked_test_ones_tensor.mean(0)
#show_image(mean1);

#mean7 = stacked_test_sevens_tensor.mean(0)
#show_image(mean7)


*2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm.*

In [5]:
#2)try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm.

def mnist_distance(a,b): return F.mse_loss(a,b).sqrt()


3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision

In [6]:
def is_1(x): return mnist_distance(x,stacked_train_ones_tensor) < mnist_distance(x,stacked_train_sevens_tensor)

#a_1 = stacked_test_ones_tensor[1]
#is_1(a_1), is_1(a_1).float()

counter_one=0
counter_seven=0

for o in stacked_test_ones_tensor:
  if is_1(o):
    counter_one+=1

for s in stacked_test_sevens_tensor:
  if not is_1(s):
    counter_seven+=1

accuracy_one = counter_one / stacked_test_ones_tensor.shape[0]
accuracy_seven = counter_seven / stacked_test_sevens_tensor.shape[0]

accuracy_one,accuracy_seven,(accuracy_one+accuracy_seven)/2


<ipython-input-5-7ff6e0a31fc8>:3: UserWarning: Using a target size (torch.Size([6301, 28, 28])) that is different to the input size (torch.Size([28, 28])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  def mnist_distance(a,b): return F.mse_loss(a,b).sqrt()
<ipython-input-5-7ff6e0a31fc8>:3: UserWarning: Using a target size (torch.Size([5834, 28, 28])) that is different to the input size (torch.Size([28, 28])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  def mnist_distance(a,b): return F.mse_loss(a,b).sqrt()


(1.0, 0.7827278958190541, 0.891363947909527)

In [7]:
print("Sevens Tensor" , stacked_test_sevens_tensor.shape[0])
print("Counter", counter_seven)

print("Ones Tensor" , stacked_test_ones_tensor.shape[0])
print("Counter", counter_one)

Sevens Tensor 1459
Counter 1142
Ones Tensor 1576
Counter 1576


****

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


In [9]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x[0:10])
print("y" , y[0:10])

tensor([[ 1.9269,  1.4873],
        [ 0.9007, -2.1055],
        [ 0.6784, -1.2345],
        [-0.0431, -1.6047],
        [-0.7521,  1.6487],
        [-0.3925, -1.4036],
        [-0.7279, -0.5594],
        [-0.7688,  0.7624],
        [ 1.6423, -0.1596],
        [-0.4974,  0.4396]])
y tensor([1., 1., 1., 1., 0., 1., 0., 0., 1., 0.])


In [10]:
print(x[:,0])

tensor([ 1.9269e+00,  9.0072e-01,  6.7842e-01, -4.3067e-02, -7.5214e-01, -3.9248e-01, -7.2788e-01, -7.6884e-01,  1.6423e+00, -4.9740e-01, -7.5813e-01,  8.0080e-01,  1.2791e+00,  6.1047e-01,
        -2.3162e-01, -2.5158e-01, -1.3847e+00, -2.2337e-01,  3.1888e-01,  3.0572e-01, -1.5576e+00, -8.7979e-01, -1.2742e+00, -1.2347e+00, -9.1382e-01,  7.8024e-02, -4.8799e-01, -8.1401e-01,
        -1.4032e+00, -6.3477e-02, -9.7807e-02, -1.1845e+00,  1.4451e+00,  2.2181e+00,  3.4665e-01, -1.0546e+00, -1.7219e-01,  5.6622e-02,  5.7501e-01, -2.2064e+00,  1.0868e-02, -1.3407e+00,
         5.3619e-01,  1.1412e+00,  7.4395e-01, -1.0495e+00, -1.7223e+00,  1.3347e+00, -2.5095e+00,  7.8459e-01,  6.4076e-01,  1.0669e+00, -1.8527e-01,  4.0476e-01,  2.6491e-01, -1.3109e-03,
        -1.4570e+00, -5.9915e-01,  7.2618e-01, -3.8907e-01, -1.2685e-02,  1.3254e-01,  1.0950e+00,  7.1997e-01,  1.9312e+00, -1.4364e+00, -1.3603e-01,  6.5474e-01,  1.1415e+00, -1.8058e+00,
        -3.7534e-01, -6.8665e-01, -9.7267e-01,  1.

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

In [11]:
def f(x, params):
    a,b,c = params
    return sigmoid(a*x[:,0] + b*x[:,1]+ c) 

print(f(x, [3,-2,1]))

tensor([9.7825e-01, 9.9963e-01, 9.9595e-01, 9.8338e-01, 1.0417e-02, 9.3275e-01, 4.8381e-01, 5.5650e-02, 9.9807e-01, 2.0240e-01, 3.1340e-02, 5.1029e-01, 9.0418e-01, 5.4039e-01, 5.5518e-01, 1.8627e-01,
        1.9599e-01, 4.2909e-02, 9.4298e-01, 9.6971e-01, 3.4567e-03, 3.9244e-01, 8.5119e-04, 1.5083e-01, 3.9527e-01, 5.4549e-01, 5.4851e-02, 5.0749e-01, 3.6203e-02, 3.6780e-01, 4.8218e-02, 4.8655e-03,
        9.7398e-01, 9.9865e-01, 9.1943e-01, 8.8385e-03, 3.6259e-01, 5.7866e-01, 9.8216e-01, 1.6023e-02, 8.4685e-01, 1.3572e-01, 8.2626e-01, 9.8688e-01, 9.8515e-01, 3.3693e-02, 7.5066e-02, 9.8266e-01,
        5.5022e-04, 9.6431e-01, 8.5268e-01, 9.9395e-01, 2.5706e-01, 8.6499e-01, 3.2047e-01, 8.3248e-01, 4.0449e-02, 1.4785e-01, 9.5240e-01, 2.2740e-01, 6.1781e-01, 4.6733e-01, 9.7354e-01, 9.1190e-01,
        9.9159e-01, 2.5932e-01, 6.4229e-02, 8.5963e-01, 9.8772e-01, 1.8919e-03, 1.0045e-01, 8.8380e-02, 2.1146e-02, 9.5056e-01, 9.0284e-01, 1.9671e-01, 5.2774e-01, 2.6425e-02, 3.6649e-03, 1.4614e-02,


In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [12]:
def mae(preds, targets): return (preds-targets.abs()).sum()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

In [13]:
lr = 1
#Initializes a Torch Tensor with 3 random parameters
params = torch.randn(3).requires_grad_()

def apply_step(params, prn=True):
    #Calculate predictions
    preds = f(x, params)
    #Loss function with mean absolute error of predictions and y 
    loss = mae(preds, y)
    # Perform back propagation with predicted values --> Calculate gradients 
    # that define how the param need to change
    loss.backward()
    #Based on Back propagation -> update parameters
    params.data -= lr * params.grad.data
    params.grad = None
    #if prn=true -> print parameter and loss
    if prn: 
        print(params);print(loss.item())
    return preds


for i in range(10): apply_step(params)

tensor([  3.5752,  -4.1180, -17.5908], requires_grad=True)
0.8166449069976807
tensor([  3.5721,  -4.1109, -17.5942], requires_grad=True)
-39.99654769897461
tensor([  3.5691,  -4.1040, -17.5976], requires_grad=True)
-39.99661636352539
tensor([  3.5661,  -4.0972, -17.6009], requires_grad=True)
-39.99668502807617
tensor([  3.5632,  -4.0905, -17.6041], requires_grad=True)
-39.99674987792969
tensor([  3.5604,  -4.0840, -17.6073], requires_grad=True)
-39.9968147277832
tensor([  3.5576,  -4.0776, -17.6104], requires_grad=True)
-39.99687576293945
tensor([  3.5549,  -4.0713, -17.6134], requires_grad=True)
-39.9969367980957
tensor([  3.5522,  -4.0651, -17.6164], requires_grad=True)
-39.99699020385742
tensor([  3.5495,  -4.0590, -17.6194], requires_grad=True)
-39.99704360961914


Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [14]:
preds = f(x, params)
wrong_preds = ((preds.round() - y).abs()).sum()
wrong_preds


tensor(40., grad_fn=<SumBackward0>)